services:
  mite-web:
    image: mayberry4477/mite-web:latest
    container_name: mite-web
    restart: unless-stopped
    ports:
      - "4050:4050"
    environment:
      - MITE_API_BASE_URL=http://192.168.4.4:4050/api
      - TZ=Asia/Tokyo
